server:
  port: 5000
  servlet:
    context-path: /api
spring:
  mvc:
    static-path-pattern: /upload/**
  resources:
    static-locations: file:src/main/resources/static
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiaozhi?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 2
    lettuce:
      pool:
        max-idle: 30
        min-idle: 10
        max-active: 30
        max-wait: 10000
  mail:
    host: smtp.qq.com
    port: 465
    username: 5565@qq.com
    password: lqydnbsebcj   # QQ邮箱授权码，非登录密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true          # 465端口用SSL
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.project.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-column-label: true
    map-underscore-to-camel-case: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    use-generated-keys: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

